trigger:
- main  # Change this to match your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Change this to match your Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies '

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to artifact directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(458ce45c-8806-423c-b4d3-951e64b8b0a0)'
    appType: 'webAppLinux'
    appName: 'Hairsalon'
    package: '$(Build.ArtifactStagingDirectory)/build'
    runtimeStack: 'NODE|18-lts'
    resourceGroupName: 'RSGTest'
    enableCustomDeployment: true
