trigger:
- main  # Change this to match your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '14.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'Install dependencies '

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(458ce45c-8806-423c-b4d3-951e64b8b0a0)'
    appType: 'webAppLinux'
    appName: 'Hairsalon'
    package: '$(Build.ArtifactStagingDirectory)/build'
    runtimeStack: 'NODE|18-lts'
    resourceGroupName: 'RSGTest'
    enableCustomDeployment: true
