trigger:
- main  # Change this to match your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'Install dependencies '

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to artifact directory'
  
- task: PublishPipelineArtifact@1
  inputs:
    artifactName: drop
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(458ce45c-8806-423c-b4d3-951e64b8b0a0)'
    appType: 'webAppLinux'
    appName: 'Hairsalon'
    package: '$(Build.ArtifactStagingDirectory)/drop'
    runtimeStack: 'NODE|18.x'
    startUpCommand: 'npm start'
