trigger:
- main  # Change this to match your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Change this to match your Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(458ce45c-8806-423c-b4d3-951e64b8b0a0)'
    appType: 'webAppLinux'
    appName: 'Hairsalon'
    package: '$(Build.ArtifactStagingDirectory)/build'
    runtimeStack: 'NODE|18-lts'
